export const actionTypes = {
	GET_TAB_DETAILS: "GET_TAB_DETAILS",
	GET_TAB_DETAILS_SUCCESS: "GET_TAB_DETAILS_SUCCESS",
	GET_TAB_DETAILS_FAILURE: "GET_TAB_DETAILS_FAILURE",
	FETCH_URL_DETAILS_SUCCESS: "FETCH_URL_DETAILS_SUCCESS",
	FETCH_URL_DETAILS_FAILURE: "FETCH_URL_DETAILS_FAILURE",
	FETCH_URL_DETAILS: "FETCH_URL_DETAILS",
	PARSE_SITE: "PARSE_SITE",
	GET_LOCAL_SITE_DATA: "RECEIVE_LOCAL_SITE_DATA",
	GET_LOCAL_SITE_DATA_SUCCESS: "GET_LOCAL_SITE_DATA_SUCCESS",
	GET_LOCAL_SITE_DATA_FAILURE: "GET_LOCAL_SITE_DATA_FAILURE"
}
