export const messageTypes = {
	GET_LOCAL_SITE_DATA: 'GET_LOCAL_SITE_DATA',
	CLOSE_EXTENSION_IN_TAB: 'CLOSE_EXTENSION_IN_TAB',
	EXTENSION_WAS_CLOSED_BY_OUTSIDE_CLICK:
		'EXTENSION_WAS_CLOSED_BY_OUTSIDE_CLICK',
	GET_CURRENT_TAB_ID: 'GET_CURRENT_TAB_ID',
	OPEN_EXTENSION_IN_TAB: 'OPEN_EXTENSION_IN_TAB'
}
